
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName":"ahsan",
    "lastName":"abbasi",
    "email":"ahsan99@test.com",
    "password":"Password12!"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6InN0ZXJvbmVAdGVzdC5jb20iLCJpYXQiOjE3NzMwODU4MDAsImV4cCI6MTc3MzA4OTQwMCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.bFc2OKQOtzwaN_Mq3DxvIitMH2D8HmxieR46LurVwz0

{
    "users":
    [
        {
            "firstName":"TestUser5",
            "lastName":"User",
            "email":"userstest121@test.com",
            "password":"Password12!"
        },
        {
            "firstName":"TestUser6",
            "lastName":"User",
            "email":"userstest111@test.com",
            "password":"Password12!"
        }
    ]
}